server:
  port: 4901
  servlet:
    session:
      timeout: 720m
  ssl:
    key-store: unshow
    key-store-password: unshow
    enabled: true

spring:
  redis:
    database: 10
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 2

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: unshow
    password: unshow
    listener:
      simple:
        default-requeue-rejected: true

mq:
  message:
    exchange: mes.exchange
    queue: mes.queue